# Generated by Django 2.0.6 on 2018-06-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('cash_sales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('credit_sales', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tips', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cash_exp', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cash_pay', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
