# Generated by Django 2.0.6 on 2018-06-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getsales', '0004_sales_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
