# Generated by Django 2.0.6 on 2018-07-10 21:08

from django.db import migrations, models
import getsales.validators


class Migration(migrations.Migration):

    dependencies = [
        ('getsales', '0007_sales_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cash_sales',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[getsales.validators.validate_decimal]),
        ),
    ]
