# Generated by Django 2.0.6 on 2018-07-10 21:14

from django.db import migrations, models
import getsales.validators


class Migration(migrations.Migration):

    dependencies = [
        ('getsales', '0008_auto_20180710_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cash_exp',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cash_pay',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cash_sales',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, validators=[getsales.validators.validate_decimal]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='credit_sales',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='savings',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tips',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
