# Generated by Django 2.0.6 on 2018-07-10 21:32

from django.db import migrations, models
import getsales.validators


class Migration(migrations.Migration):

    dependencies = [
        ('getsales', '0010_auto_20180710_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cash_exp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cash_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sales',
            name='cash_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, validators=[getsales.validators.validate_decimal]),
        ),
        migrations.AlterField(
            model_name='sales',
            name='credit_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sales',
            name='notes',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='sales',
            name='savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tips',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
